FROM node:20-alpine

WORKDIR /app

COPY package.json yarn.lock ./
COPY frontend/package.json frontend/

RUN yarn install

COPY frontend frontend/

WORKDIR /app/frontend

EXPOSE 5173

CMD ["yarn", "dev"]
